#!/bin/sh

FLAGS=""
if [[ ! -z "${PLUGIN_DEPTH}" ]]; then
	FLAGS="--depth=${PLUGIN_DEPTH}"
fi

if [ ! -d .git ]; then
	git init
	git remote add origin ${DRONE_REMOTE_URL}
fi

set -e
set -x

CURRENT_BRANCH=$(echo ${DRONE_COMMIT_REFSPEC} | awk  -F ':' '{ print $1 }')
BASE_BRANCH=$(echo ${DRONE_COMMIT_REFSPEC} | awk  -F ':' '{ print $2 }')

git fetch ${FLAGS} origin ${CURRENT_BRANCH}
# git fetch ${FLAGS} origin ${BASE_BRANCH}

git checkout ${CURRENT_BRANCH}
git pull --rebase origin ${BASE_BRANCH}
