pipeline:
  publish-image:
    image: plugins/docker
    repo: prontopro/drone-git
    dockerfile: Dockerfile
    secrets: [docker_username, docker_password]
    tags:
      - ${DRONE_COMMIT_BRANCH}
      - ${DRONE_COMMIT_BRANCH}-${DRONE_BUILD_NUMBER}
    when:
      branch:
        - master
      event:
        - push
